jobs:
  - job: Build_PSCore_MacOS1013
    pool:
      vmImage: macOS-latest
    steps:
      - script: |
          brew update
          brew tap caskroom/cask
          brew install mono-libgdiplus
          brew cask install powershell
        displayName: "Install PowerShell Core"
      - script: |
          pwsh -c '.\PSSharedGoods.Tests.ps1'
        displayName: "Run Pester Tests"
